services:
  discovery-service:
    container_name: discovery-service
    build: ./discovery-service
    ports:
    - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f","http://192.168.134.3:8761/actuator/health" ]
      interval: 10s
      retries: 3
  gateway-service:
    container_name: gateway-service
    build: ./gateway-service
    restart: always
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.134.3:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://192.168.134.3:8888/actuator/health" ]
      interval: 10s
      retries: 5
    depends_on:
      discovery-service:
        condition: service_healthy
  security-service:
    container_name: security-service
    build: ./security-service
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.134.3:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://192.168.134.3:8888/SECURITY-SERVICE/actuator/health" ]
      interval: 15s
      retries: 5
    depends_on:
      gateway-service:
        condition: service_healthy
  customer-service:
    container_name: customer-service
    build: ./customer-service
    restart: always
    ports:
      - '8090:8090'
    expose:
      - '8090'
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.134.3:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://192.168.134.3:8888/CUSTOMER-SERVICE/actuator/health" ]
      interval: 15s
      retries: 5
    depends_on:
      security-service:
        condition: service_healthy
  inventory-service:
    container_name: inventory-service
    build: ./inventory-service
    restart: always
    ports:
      - '8085:8085'
    expose:
      - '8085'
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.134.3:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://192.168.134.3:8888/INVENTORY-SERVICE/actuator/health" ]
      interval: 15s
      retries: 5
    depends_on:
      security-service:
        condition: service_healthy
  billing-service:
    container_name: billing-service
    build: ./billing-service
    restart: always
    ports:
      - '8095:8095'
    expose:
      - '8095'
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.134.3:8761/eureka
    depends_on:
      customer-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy